"""baseline schema

Revision ID: d9f1a136d398
Revises: 
Create Date: 2026-07-11 17:09:37.792913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f1a136d398'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('case_id', sa.String(length=8), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('draft_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_case_id'), 'claims', ['case_id'], unique=False)
    op.create_table('documents',
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('type', sa.Enum('INVOICE', 'PURCHASE_ORDER', 'CONTRACT', 'DELIVERY_DOCKET', 'REMITTANCE_ADVICE', 'PROMO_AGREEMENT', 'UNKNOWN', name='documenttype'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_json', sa.Text(), nullable=True),
    sa.Column('verification_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=8), nullable=True),
    sa.Column('doc_date', sa.String(length=32), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('case_id', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_case_id'), 'reconciliations', ['case_id'], unique=False)
    op.create_table('case_membership_overrides',
    sa.Column('case_id', sa.String(length=8), nullable=False),
    sa.Column('document_id', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'document_id', name='uq_case_override')
    )
    op.create_index(op.f('ix_case_membership_overrides_case_id'), 'case_membership_overrides', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_membership_overrides_document_id'), 'case_membership_overrides', ['document_id'], unique=False)
    op.create_table('doc_links',
    sa.Column('doc_a_id', sa.String(length=8), nullable=False),
    sa.Column('doc_b_id', sa.String(length=8), nullable=False),
    sa.Column('case_id', sa.String(length=8), nullable=True),
    sa.Column('value_norm', sa.String(length=128), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doc_a_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['doc_b_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_a_id', 'doc_b_id', 'value_norm', name='uq_doc_link')
    )
    op.create_index(op.f('ix_doc_links_case_id'), 'doc_links', ['case_id'], unique=False)
    op.create_index(op.f('ix_doc_links_doc_a_id'), 'doc_links', ['doc_a_id'], unique=False)
    op.create_index(op.f('ix_doc_links_doc_b_id'), 'doc_links', ['doc_b_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('case_id', sa.String(length=8), nullable=False),
    sa.Column('reconciliation_id', sa.String(length=8), nullable=True),
    sa.Column('document_id', sa.String(length=8), nullable=True),
    sa.Column('claim_id', sa.String(length=8), nullable=True),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('delta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_case_id'), 'exceptions', ['case_id'], unique=False)
    op.create_table('invoices',
    sa.Column('document_id', sa.String(length=8), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_date', sa.String(length=32), nullable=True),
    sa.Column('supplier_name', sa.String(length=256), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_table('line_items',
    sa.Column('invoice_id', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_items_invoice_id'), 'line_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_items_invoice_id'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_exceptions_case_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_doc_links_doc_b_id'), table_name='doc_links')
    op.drop_index(op.f('ix_doc_links_doc_a_id'), table_name='doc_links')
    op.drop_index(op.f('ix_doc_links_case_id'), table_name='doc_links')
    op.drop_table('doc_links')
    op.drop_index(op.f('ix_case_membership_overrides_document_id'), table_name='case_membership_overrides')
    op.drop_index(op.f('ix_case_membership_overrides_case_id'), table_name='case_membership_overrides')
    op.drop_table('case_membership_overrides')
    op.drop_index(op.f('ix_reconciliations_case_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_claims_case_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_table('cases')
    # ### end Alembic commands ###
